services:
  calendar:
    image: ghcr.io/nikojunttila/calendar:latest

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: calendar
    networks:
      - app-network
    ports:
      - "7331:7331"
    volumes:
      - calendar-data:/app/data
    env_file:
      - .env
    environment:
      - HTTP_LISTEN_ADDR=:7331
      - DB_DRIVER=sqlite3
      - DB_NAME=/app/data/app.db
      - MIGRATION_DIR=migrations
    restart: unless-stopped
volumes:
  calendar-data:
    driver: local
# saves data to /var/lib/docker/volumes/[project-name]_calendar-data/_data
# docker volume inspect [project-name]_calendar-data
networks:
  # Create network for the app where we connect cloudflared tunnel
  app-network:
    external: true