
services:
  calendar:
    build: .
    container_name: calendar
    restart: unless-stopped
    ports:
      - "5000:7331"
    volumes:
      - calendar-data:/app/data
    environment:
      # App Env
      - SUPERKIT_ENV=production
      # Network
      - HTTP_LISTEN_ADDR=:7331
      # Database
      - DB_DRIVER=libsql
      - DB_URL=
      # Secrets and Auth
      - SUPERKIT_SECRET=716b781364fb764e5628c99a2987f1d18d3f4eea90dd671a7281de7fc3dec12c
      - SUPERKIT_AUTH_REDIRECT_AFTER_LOGIN=/profile
      - SUPERKIT_AUTH_SESSION_EXPIRY_IN_HOURS=48
      - SUPERKIT_AUTH_SKIP_VERIFY=true
      - SUPERKIT_AUTH_EMAIL_VERIFICATION_EXPIRY_IN_HOURS=11
      # Third Party
      - MG_API_KEY=<Your API Key>
      - MG_EMAIL=randomderp98@gmail.com

volumes:
  calendar-data:
    driver: local

