
services:
  calendar:
    build: .
    container_name: calendar
    restart: unless-stopped
    ports:
      - "5000:7331"
    volumes:
      - calendar-data:/app/data
    env_file:
      - .env
    environment:
      - HTTP_LISTEN_ADDR=:7331
      - DB_DRIVER=sqlite3
      - DB_NAME=/app/data/app.db
      - MIGRATION_DIR=migrations
      - LOCALE_DIR=/app/translations/locales

volumes:
  calendar-data:
    driver: local

